[tool.poetry]
name = "ozcore"
version = "0.0.0" # will be overwritten by poetry-dynamic-versioning 
description = "My core."
authors = ["Ozgur Kalan <ozgurkalan@gmail.com>"]
readme = "README.rst"
repository = "https://github.com/ozgurkalan/OzCore"
license = "GPL-3.0-or-later"
classifiers =[
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3.8",
    "Operating System :: MacOS",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
] 

[tool.poetry.dependencies]
python = "^3.8"
scipy = "^1.6.1"
numpy = "^1.20.1"
pandas = "^1.2.3"
pandas-datareader = "^0.9.0"
pandas-profiling = "^2.11.0"
ipykernel = "^5.5.0"
nbformat = "^5.1.2"
qgrid = "^1.3.1"
ipyaggrid = "^0.2.1"
typeguard = "^2.11.1"
SQLAlchemy = "^1.4.2"
alembic = "^1.5.7"
requests = "^2.25.1"
lxml = "^4.6.3"
html5lib = "^1.1"
beautifulsoup4 = "^4.9.3"
urllib3 = "^1.26.4"
dynaconf = "^3.1.4"
python-dotenv = "^0.15.0"
html2text = "^2020.1.16"
markdown2 = "^2.4.0"
emoji = "^1.2.0"
Faker = "^6.6.2"
google-trans-new = "^1.1.9"
python-docx = "^0.8.10"
docxcompose = "^1.3.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^2.11.1"
pytest-remotedata = "^0.3.2"
black = "^20.8b1"
setuptools = "^54.1.3"
tox = "^3.23.0"
dunamai = "^1.5.4"
poetry-dynamic-versioning = "^0.12.4"
Sphinx = "^3.5.3"
sphinx-autobuild = "^2021.3.14"
sphinx-rtd-theme = "^0.5.1"
sphinxcontrib-napoleon = "^0.7"
myst-parser = "^0.13.5"
rstcheck = "^3.3.1"
recommonmark = "^0.7.1"

[tool.poetry.extras]
test = ["pytest"]


[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"

[tool.black]
target-version = ['py38']
exclude = '''
(
    asv_bench/env
  | \.egg
  | \.git
  | \.hg
  | \.mypy_cache
  | \.nox
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | setup.py
)
'''

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"
